version: 2
# .goreleaser.yml

builds:
  - binary: ecs-tool
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  - vendor: Ekini
    homepage: https://github.com/ekini/ecs-tool

    maintainer: DevOps team
    description: Runs commands on ECS cluster
    license: Apache 2.0
    formats:
      - deb
      - rpm
